//! Local "dirty" queue for book/list creates made while the sandbox agent is
//! offline. The sandbox is normally the single source of truth (see
//! `services::routing`), but creating a book/list while the agent is down would
//! otherwise be silently lost. We persist the intent to a small local file and
//! replay it against the agent once it reconnects.
//!
//! Scope is deliberately narrow: only *creation* of empty books/lists is queued.
//! Content edits still require an already-synced book/list.

use tauri::State;

use crate::models::list::ListField;
use crate::services::routing::{agent_rpc, agent_url};
use crate::state::AppState;

/// A queued create. `local_id` and `created_at` are generated by the frontend
/// (webview `crypto.randomUUID()` / `Date`), so this layer needs no uuid/clock.
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct PendingCreate {
    pub local_id: String,
    /// "book" | "list"
    pub kind: String,
    pub name: String,
    /// Schema for list creates; empty for books.
    #[serde(default)]
    pub fields: Vec<ListField>,
    pub created_at: String,
}

/// Outcome of a flush attempt.
#[derive(serde::Serialize)]
pub struct FlushResult {
    pub synced: usize,
    pub remaining: usize,
    pub errors: Vec<String>,
}

fn queue_path(state: &AppState) -> std::path::PathBuf {
    state.config_dir.join("pending_creates.json")
}

fn read_queue(state: &AppState) -> Vec<PendingCreate> {
    let path = queue_path(state);
    std::fs::read_to_string(&path)
        .ok()
        .and_then(|c| serde_json::from_str(&c).ok())
        .unwrap_or_default()
}

fn write_queue(state: &AppState, queue: &[PendingCreate]) -> Result<(), String> {
    let _ = std::fs::create_dir_all(&state.config_dir);
    let path = queue_path(state);
    let content = serde_json::to_string_pretty(queue).map_err(|e| e.to_string())?;
    std::fs::write(&path, content).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn list_pending_creates(state: State<AppState>) -> Vec<PendingCreate> {
    read_queue(&state)
}

#[tauri::command]
pub fn enqueue_pending_create(
    entry: PendingCreate,
    state: State<AppState>,
) -> Result<Vec<PendingCreate>, String> {
    let mut queue = read_queue(&state);
    queue.push(entry);
    write_queue(&state, &queue)?;
    Ok(queue)
}

#[tauri::command]
pub fn remove_pending_create(
    local_id: String,
    state: State<AppState>,
) -> Result<Vec<PendingCreate>, String> {
    let mut queue = read_queue(&state);
    queue.retain(|e| e.local_id != local_id);
    write_queue(&state, &queue)?;
    Ok(queue)
}

/// Replay every queued create against the agent, dropping each entry only after
/// its create succeeds. No-op (with everything left queued) when the agent isn't
/// connected. NOTE: a crash between a successful agent create and the queue write
/// below could replay that create on the next flush and double-create the empty
/// container — acceptable for create-only intents.
#[tauri::command]
pub async fn flush_pending_creates(state: State<'_, AppState>) -> Result<FlushResult, String> {
    let url = match agent_url(&state) {
        Some(u) => u,
        None => {
            let remaining = read_queue(&state).len();
            return Ok(FlushResult { synced: 0, remaining, errors: vec![] });
        }
    };

    let queue = read_queue(&state);
    let mut remaining: Vec<PendingCreate> = Vec::new();
    let mut synced = 0usize;
    let mut errors: Vec<String> = Vec::new();

    for entry in queue {
        let (method, params) = if entry.kind == "list" {
            (
                "lists/create_list",
                serde_json::json!({ "name": entry.name, "fields": entry.fields }),
            )
        } else {
            ("books/create_book", serde_json::json!({ "name": entry.name }))
        };

        match agent_rpc::<serde_json::Value>(&url, method, params).await {
            Ok(_) => synced += 1,
            Err(e) => {
                errors.push(format!("{} \"{}\": {}", entry.kind, entry.name, e));
                remaining.push(entry);
            }
        }
    }

    write_queue(&state, &remaining)?;
    Ok(FlushResult { synced, remaining: remaining.len(), errors })
}
